version: '3.9'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      webapp-infra:
    environment:
      VIRTUAL_HOST: domain.example.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: domain.example.com
      LETSENCRYPT_EMAIL: contact@domain.example.com
    volumes:
      - grafana-data:/var/lib/grafana  # 호스트의 ./data 디렉토리를 컨테이너의 /var/lib/grafana와 매핑
    deploy:
      resources:
        limits:
          memory: 700m  # RAM 제한: 50MB
        reservations:
          memory: 30m  # 최소 예약 메모리: 30MB
    restart: unless-stopped

volumes:
  grafana-data:  # 네임드 볼륨 정의 (필요 시 사용 가능)
networks:
  webapp-infra:
    external: true