version: '3.8'

services:
  exporter:
    build: 
      context: .
    container_name: 'exporter'
    image: exporter:1.0
    ports:
    - "2055:2055/udp"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

