global:
  scrape_interval: 15s  # 데이터 수집 간격

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'localhost:9100'  # Node Exporter의 주소
          - '10.0.0.1:9100'   # 추가 Node Exporter 대상
    metrics_path: /metrics  # Node Exporter 기본 경로
